title: Yirui Zhang's Homepage
page-top-title: Yirui Zhang
top-section-bg-text: Computer Science
home-subtitle: Yirui Zhang&ensp;|&ensp;张一瑞
copyright-text: '&copy; Yirui Zhang 2025-2026. All Rights Reserved.'
